AllCops:
  Exclude:
    - 'Gemfile'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 80

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec-rspec/**/*'
    - 'db/migrations/**/*'
    - 'tasks/**/*'

Style/UnpackFirst:
  Enabled: false
